logging:
  level:
    org:
      springframework:
        security: info
    com.google.api.client: info
spring:
  application:
    name: social
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liRa0GHrCPbEpAMf
            client-secret: a4572d99622276afb6f8b75f5f819639a181da00
            redirect-uri: http://localhost:8080/login/oauth2/code/github
            scope:
              - email
              - profile
              - offline_access
          google:
            client-id: 768944951916-ik6spf8bdt6f9jk9l96u2f1bos12upgl.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - https://www.googleapis.com/auth/userinfo.email
              - https://www.googleapis.com/auth/userinfo.profile
              - https://www.googleapis.com/auth/calendar
              - https://www.googleapis.com/auth/calendar.events
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=consent&access_type=offline
  jpa:
    generate-ddl: true
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/family_book?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    hikari:
      minimum-idle: 4
      maximum-pool-size: 50