spring:
  application:
    name: social
  security:
    oauth2:
      client:
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=consent&access_type=offline
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
          microsoft:
            authorization-uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
            user-name-attribute: oid
            jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
        registration:
          google:
            provider: google
            client-id: 768944951916-ik6spf8bdt6f9jk9l96u2f1bos12upgl.apps.googleusercontent.com
            client-name: Login with Google
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - https://www.googleapis.com/auth/userinfo.email
              - https://www.googleapis.com/auth/userinfo.profile
              - https://www.googleapis.com/auth/calendar.readonly
          microsoft:
            provider: microsoft
            client-id: a1a42d95-2a30-495e-ab6e-311e9611b801
            client-name: Login with Microsoft
            client-secret: 4bs8Q~CRCzVd_qACFaLOv5tFUWhpaUHDSpAKJahj
            redirect-uri: http://localhost:8080/login/oauth2/code/
            authorization-grant-type: authorization_code
            scope:
              - offline_access
              - openid
              - email
              - profile
              - Calendars.Read
              - Channel.Create
              - Channel.Delete.All
              - Channel.ReadBasic.All
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/family_book?useUnicode=true&characterEncoding=utf-8
    username: family_book
    password: family_book
    hikari:
      minimum-idle: 4
      maximum-pool-size: 50
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 15


server:
  port: 8080
logging:
  level:
    org:
      springframework:
        security: trace
    com.qimiao.social: warn