logging:
  level:
    org:
      springframework:
        security: trace
    com.google.api.client: info
spring:
  application:
    name: social
  security:
    oauth2:
      client:
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=consent&access_type=offline
          azure:
            issuer-uri: https://login.microsoftonline.com/cf7cc825-b528-4694-879e-c25c0cd91ac7/v2.0
        registration:
          google:
            provider: google
            client-id: 768944951916-ik6spf8bdt6f9jk9l96u2f1bos12upgl.apps.googleusercontent.com
            client-name: Login with Google
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - https://www.googleapis.com/auth/userinfo.email
              - https://www.googleapis.com/auth/userinfo.profile
              - https://www.googleapis.com/auth/calendar.readonly
          azure:
              provider: azure
              client-id: a1a42d95-2a30-495e-ab6e-311e9611b801
              client-name: Login with Azure
              client-secret: 4bs8Q~CRCzVd_qACFaLOv5tFUWhpaUHDSpAKJahj
              redirect-uri: http://localhost:8080/login/oauth2/code/
              authorization-grant-type: authorization_code
              scope:
                - openid
                - email
                - profile

  jpa:
    generate-ddl: true
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/family_book?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    hikari:
      minimum-idle: 4
      maximum-pool-size: 50