langchain4j:
  redis:
    host: 192.168.124.3
    password:
    port: 6379
#  ollama:
#    chat-model:
#      base-url: http://192.168.124.3:11434
#      model-name: deepseek-r1:14b
#      log-requests: true
#      log-responses: true
#      temperature: 0.3
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      model-name: deepseek-chat
      api-key: sk-ee9b5e20d4f546e18f83aadf69d79d82

logging:
  level:
    root: debug
    dev.langchain4j: debug
    dev:
      langchain4j:
        model: warn