spring:
  application:
    name: base-login-auth
  datasource:
    hikari:
      poolName: HikariPool
      minimum-idle: 5
      maximum-pool-size: 50
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@172.30.38.135:1521:alidev
    username: DEV_FSPF_BASIC
    password: sKw12op